### ISSUE TITLE
attackController

### ISSUE THREAD

**Issue by 89gsc** [kaaku/screeps#2]
When occupying a room it kills all creeps and structures (it was fun to watch) but it does not attack the controller meaning you need to wait the timer, is this was possible to speed up takeover it would allow faster progression. 

Example Room: https://screeps.com/a/#!/room/E18N38

**Comment by 89gsc** [comment]
I think this is more to do with the flag being cleared as soon as all hostiles are killed, is the room controller not counted as hostile?

**Comment by 89gsc** [comment]
Might be more to do with GCL actually looking at it.

**Comment by kaaku** [comment]
Yeah, at the moment the occupation flag is just cleared and that's the end of it. I'm actually currently working on the necessary logic for attacking a hostile room's controller downgrade timer. But when I wrote the occupation logic it wasn't relevant yet, as you need to have a room with RCL 7 or higher to be able to build a creep that can attack hostile controllers. The creep needs to have at least 5 CLAIM parts in order to attack the timer, and those alone cost 3000 energy. A room with RCL 6 has an energy capacity of 2300.
